# Generated by Django 3.0 on 2020-12-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('home_phone', models.CharField(max_length=20)),
                ('birth_date', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.IntegerField(choices=[(0, 'male'), (1, 'female')])),
                ('street', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact_1_name', models.CharField(max_length=50)),
                ('contact_1_phone', models.CharField(max_length=20)),
                ('contact_2_name', models.CharField(max_length=50)),
                ('contact_2_phone', models.CharField(max_length=20)),
            ],
        ),
    ]
