# Generated by Django 3.0 on 2020-12-25 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField(unique=True)),
                ('level', models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=2)),
            ],
            options={
                'ordering': ['class_number'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Father',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_ID', models.IntegerField(blank=True, null=True, unique=True)),
                ('phone', models.IntegerField()),
                ('job', models.CharField(max_length=150)),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_ID', models.IntegerField(blank=True, null=True, unique=True)),
                ('phone', models.IntegerField()),
                ('job', models.CharField(max_length=150)),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('classrooms_number', models.IntegerField(blank=True, null=True, verbose_name='Number of classes')),
                ('teachers_number', models.IntegerField(blank=True, null=True, verbose_name='Number of teachers in all school')),
                ('students_number', models.IntegerField(blank=True, null=True, verbose_name='Number of students in all school')),
                ('location', models.CharField(max_length=280)),
                ('manager', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='specializations/')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(help_text='Format: <b>Year:Month:Day Hour:Minute</b> <i>example: 2021-2-26 10:00</i>')),
                ('duration', models.SmallIntegerField()),
                ('mark', models.SmallIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_ID', models.IntegerField(blank=True, null=True, unique=True)),
                ('address', models.CharField(max_length=264)),
                ('phone', models.IntegerField()),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/')),
                ('achievements', models.TextField(blank=True, max_length=1000, null=True)),
                ('gender', models.IntegerField(choices=[(0, 'male'), (1, 'female')])),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Specialization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_ID', models.IntegerField(blank=True, null=True, unique=True)),
                ('academic_number', models.IntegerField(unique=True)),
                ('home_phone', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=280)),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('gender', models.IntegerField(choices=[(0, 'male'), (1, 'female')])),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.Classroom')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Father')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Mother')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_file', models.FileField(upload_to='materials/', verbose_name='File')),
                ('title', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Test')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_of_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Teacher'),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('0', 'saturday'), ('1', 'sunday'), ('2', 'monday'), ('3', 'tuesday'), ('4', 'wednesday'), ('5', 'thursday'), ('6', 'friday')], max_length=1)),
                ('class_number_in_day', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_classes', to='school.Course')),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'ordering': ['day'],
            },
        ),
    ]
