# Generated by Django 3.0 on 2020-08-28 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField(unique=True)),
                ('level', models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=2)),
            ],
            options={
                'ordering': ['class_number'],
                'permissions': (('can_see_classrooms', 'Can see Classrooms'),),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('picture', models.ImageField(upload_to='courses')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Father',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('national_id', models.IntegerField(unique=True)),
                ('phone', models.IntegerField()),
                ('job', models.CharField(max_length=150)),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
            ],
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('national_id', models.IntegerField(unique=True)),
                ('phone', models.IntegerField()),
                ('job', models.CharField(max_length=150)),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('classes_number', models.IntegerField(verbose_name='Number of classes')),
                ('teachers_number', models.IntegerField(verbose_name='Number of teachers in all school')),
                ('students_number', models.IntegerField(verbose_name='Number of students in all school')),
                ('location', models.CharField(max_length=280)),
                ('manger', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=264)),
                ('phone', models.IntegerField()),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
                ('photo', models.ImageField(upload_to='teachers/')),
                ('achievements', models.TextField(blank=True, max_length=1000, null=True)),
                ('is_teacher', models.BooleanField(default=True)),
                ('classrooms', models.ManyToManyField(related_name='classroom_teachers', to='school.Classroom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'permissions': (('can_edit_grades', 'Edit students grades'),),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('home_phone', models.IntegerField()),
                ('address', models.CharField(max_length=280)),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
                ('photo', models.ImageField(upload_to='students/')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.Classroom')),
                ('courses', models.ManyToManyField(to='school.Course')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Father')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Mother')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Test')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_of_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Teacher'),
        ),
    ]
