# Generated by Django 3.0 on 2020-08-22 08:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField()),
                ('level', models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Father',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('national_id', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('work', models.CharField(max_length=150)),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
            ],
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('national_id', models.IntegerField(validators=[django.core.validators.MaxValueValidator(14), django.core.validators.MinValueValidator(14)])),
                ('phone', models.IntegerField()),
                ('work', models.CharField(max_length=150)),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_phone', models.IntegerField()),
                ('father', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Father')),
                ('mother', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Mother')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('classes_number', models.IntegerField(verbose_name='Number of classes')),
                ('teachers_number', models.IntegerField(verbose_name='Number of teachers in all school')),
                ('students_number', models.IntegerField(verbose_name='Number of students in all school')),
                ('location', models.CharField(max_length=280)),
                ('manger', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=264)),
                ('phone', models.IntegerField()),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
                ('classrooms', models.ManyToManyField(to='school.Classroom')),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Course')),
            ],
            options={
                'permissions': (('can_edit_grades', 'Edit students grades'),),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('home_phone', models.IntegerField()),
                ('address', models.CharField(max_length=280)),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
                ('level', models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=2)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='school.Classroom')),
                ('parents', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Parents')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='classroom_teachers',
            field=models.ManyToManyField(to='school.Teacher'),
        ),
    ]
