# Generated by Django 3.0 on 2020-12-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(choices=[('1', 'Mothers'), ('2', 'Fathers'), ('2', 'Fathers and Mothers')], max_length=20, verbose_name='To')),
                ('subject', models.CharField(max_length=50, verbose_name='Subject')),
                ('body', models.CharField(max_length=3000, verbose_name='Body')),
            ],
        ),
    ]
