# Generated by Django 3.0 on 2020-08-28 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20200828_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Father'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Mother'),
        ),
    ]
