# Generated by Django 3.0 on 2020-08-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20200822_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parents',
        ),
        migrations.DeleteModel(
            name='Parents',
        ),
    ]
