# Generated by Django 3.0 on 2020-09-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_teacher_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='specialization',
            field=models.CharField(default='teacher', max_length=64),
            preserve_default=False,
        ),
    ]
