# Generated by Django 3.0 on 2020-09-16 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_teacher_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='classrooms',
        ),
    ]
