# Generated by Django 3.0 on 2020-08-22 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20200822_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Father'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Mother'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='classroom_teachers',
            field=models.ManyToManyField(null=True, to='school.Teacher'),
        ),
    ]
