# Generated by Django 3.0 on 2020-09-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_teacher_classrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='classrooms',
            field=models.ManyToManyField(related_name='classroom_teachers', to='school.Classroom'),
        ),
    ]
