# Generated by Django 3.0 on 2020-08-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20200822_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='classroom_teachers',
            field=models.ManyToManyField(blank=True, null=True, to='school.Teacher'),
        ),
    ]
