# Generated by Django 3.0 on 2020-08-31 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20200831_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.Student'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.Test'),
        ),
    ]
