# Generated by Django 3.0 on 2020-08-31 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20200831_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Test'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('test', 'student')},
        ),
    ]
