# Generated by Django 3.0 on 2020-08-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20200822_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(default='1', upload_to=''),
            preserve_default=False,
        ),
    ]
