# Generated by Django 3.0 on 2020-08-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20200822_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['name'], 'permissions': (('can_edit_grades', 'Edit students grades'),)},
        ),
        migrations.AddField(
            model_name='course',
            name='picture',
            field=models.ImageField(default='1', upload_to='courses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='national_id',
            field=models.IntegerField(default='1', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroom',
            name='class_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='father',
            name='national_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='mother',
            name='national_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(upload_to='teachers/'),
        ),
    ]
