# Generated by Django 3.0 on 2020-08-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20200823_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='achievements',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
