# Generated by Django 3.0 on 2020-08-24 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20200824_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='father',
            old_name='work',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='mother',
            old_name='work',
            new_name='job',
        ),
    ]
