# Generated by Django 3.0 on 2020-08-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20200824_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='1', upload_to='students/'),
            preserve_default=False,
        ),
    ]
