# Generated by Django 3.0 on 2020-08-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_remove_student_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['class_number'], 'permissions': (('can_see_classrooms', 'Can see Classrooms'),)},
        ),
    ]
