# Generated by Django 3.0 on 2020-08-26 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_auto_20200826_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
