# Generated by Django 3.0 on 2020-08-26 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_auto_20200826_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_of_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Teacher'),
        ),
    ]
