# Generated by Django 3.0 on 2020-08-26 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0028_course_teacher_of_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Classroom'),
        ),
    ]
