# Generated by Django 3.0 on 2020-08-26 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_teacher_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='courses',
        ),
    ]
