# Generated by Django 3.0 on 2020-08-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0033_teacher_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='courses',
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='school.Course'),
        ),
    ]
