# Generated by Django 3.0 on 2020-08-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0034_auto_20200826_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='student_courses', to='school.Course'),
        ),
    ]
