# Generated by Django 3.0 on 2020-08-27 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0036_auto_20200828_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Classroom'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_of_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.Classroom'),
        ),
        migrations.AlterField(
            model_name='student',
            name='father',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.Father'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='mother',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='school.Mother'),
            preserve_default=False,
        ),
    ]
